from fastapi import FastAPI, Query
from fastapi.middleware.cors import CORSMiddleware
import pandas as pd

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load the Excel file into memory
try:
    df = pd.read_excel("UHE_Visual_Product_Catalog_AutoGenerated.xlsx")
except Exception as e:
    df = None
    print("❌ Error loading Excel file:", e)

@app.get("/")
def read_root():
    return {"message": "UHE Product API is Live!"}

@app.get("/getProduct")
def get_product(productName: str = Query(..., description="Product name to look up")):
    if df is None:
        return {"error": "Product catalog not loaded. Please check server logs."}

    # Normalize and strip input
    cleaned_input = productName.strip().lower()

    try:
        # Clean up column values to avoid NoneType errors
        matches = df[df["Product Name"].astype(str).str.strip().str.lower() == cleaned_input]

        if matches.empty:
            return {"error": f"No matches found for '{productName}'"}

        # Check required fields
        required_fields = [
            "Product Name",
            "Variant",
            "Brand",
            "Category",
            "Prompt Template",
            "Image URL"
        ]
        valid_rows = matches.dropna(subset=required_fields)

        if valid_rows.empty:
            return {"error": f"Matching rows for '{productName}' are missing required fields"}

        return valid_rows.to_dict(orient="records")

    except Exception as e:
        return {"error": f"Internal processing error: {str(e)}"}
