from fastapi import FastAPI, Query
from fastapi.middleware.cors import CORSMiddleware
import pandas as pd

# Initialize FastAPI app
app = FastAPI()

# Enable CORS (for GPT and browser access)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load the Excel catalog into memory
df = pd.read_excel("UHE_Visual_Product_Catalog_AutoGenerated.xlsx")

@app.get("/")
def read_root():
    return {"message": "UHE Product API is Live!"}

@app.get("/getProduct")
def get_product(productName: str = Query(..., description="Product name to look up")):
    # Strip whitespace and match case-insensitive
    cleaned_input = productName.strip().lower()
    matches = df[df["Product Name"].str.strip().str.lower() == cleaned_input]

    if matches.empty:
        return {"error": f"No matches found for '{productName}'"}

    # Filter rows that have all required fields
    required_fields = [
        "Product Name",
        "Variant",
        "Brand",
        "Category",
        "Prompt Template",
        "Image URL"
    ]
    valid_rows = matches.dropna(subset=required_fields)

    if valid_rows.empty:
        return {"error": f"Matching rows for '{productName}' are missing required fields"}

    # Return all valid matches as a list of dictionaries
    return valid_rows.to_dict(orient="records")
